name: Periodical Healthcheck

on:
  push:
    branches:
      - master

jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://thawing-retreat-21942.herokuapp.com/health
          follow-redirect: false
          max-attempts: 2
          retry-delay: 5s
          retry-all: true
